/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as HorecaRouteImport } from './routes/horeca'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as HorecaIdRouteImport } from './routes/horeca.$id'
import { Route as HorecaBookingIdRouteImport } from './routes/horeca.booking.$id'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const HorecaRoute = HorecaRouteImport.update({
  id: '/horeca',
  path: '/horeca',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HorecaIdRoute = HorecaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HorecaRoute,
} as any)
const HorecaBookingIdRoute = HorecaBookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => HorecaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/horeca': typeof HorecaRouteWithChildren
  '/success': typeof SuccessRoute
  '/horeca/$id': typeof HorecaIdRoute
  '/product/$id': typeof ProductIdRoute
  '/horeca/booking/$id': typeof HorecaBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/horeca': typeof HorecaRouteWithChildren
  '/success': typeof SuccessRoute
  '/horeca/$id': typeof HorecaIdRoute
  '/product/$id': typeof ProductIdRoute
  '/horeca/booking/$id': typeof HorecaBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/horeca': typeof HorecaRouteWithChildren
  '/success': typeof SuccessRoute
  '/horeca/$id': typeof HorecaIdRoute
  '/product/$id': typeof ProductIdRoute
  '/horeca/booking/$id': typeof HorecaBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/favorites'
    | '/horeca'
    | '/success'
    | '/horeca/$id'
    | '/product/$id'
    | '/horeca/booking/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/favorites'
    | '/horeca'
    | '/success'
    | '/horeca/$id'
    | '/product/$id'
    | '/horeca/booking/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/favorites'
    | '/horeca'
    | '/success'
    | '/horeca/$id'
    | '/product/$id'
    | '/horeca/booking/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRoute
  CheckoutRoute: typeof CheckoutRoute
  FavoritesRoute: typeof FavoritesRoute
  HorecaRoute: typeof HorecaRouteWithChildren
  SuccessRoute: typeof SuccessRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horeca': {
      id: '/horeca'
      path: '/horeca'
      fullPath: '/horeca'
      preLoaderRoute: typeof HorecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horeca/$id': {
      id: '/horeca/$id'
      path: '/$id'
      fullPath: '/horeca/$id'
      preLoaderRoute: typeof HorecaIdRouteImport
      parentRoute: typeof HorecaRoute
    }
    '/horeca/booking/$id': {
      id: '/horeca/booking/$id'
      path: '/booking/$id'
      fullPath: '/horeca/booking/$id'
      preLoaderRoute: typeof HorecaBookingIdRouteImport
      parentRoute: typeof HorecaRoute
    }
  }
}

interface HorecaRouteChildren {
  HorecaIdRoute: typeof HorecaIdRoute
  HorecaBookingIdRoute: typeof HorecaBookingIdRoute
}

const HorecaRouteChildren: HorecaRouteChildren = {
  HorecaIdRoute: HorecaIdRoute,
  HorecaBookingIdRoute: HorecaBookingIdRoute,
}

const HorecaRouteWithChildren =
  HorecaRoute._addFileChildren(HorecaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRoute,
  CheckoutRoute: CheckoutRoute,
  FavoritesRoute: FavoritesRoute,
  HorecaRoute: HorecaRouteWithChildren,
  SuccessRoute: SuccessRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
